service:
  type: internal
server:
  port: 8585
spring:
  application:
    name: dezhban
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:h2:mem:dezhban;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS DEZHBAN
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      schema: DEZHBAN
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db-changes/dezhban-changelog-master.xml
    contexts: table-creation, sequence-creation, populate-data
    default-schema: DEZHBAN
    liquibase-schema: DEZHBAN
    drop-first: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ "*" ]
      base-path: /web
  server:
    port: 8586
    base-path: /management
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p  --- : %m%n%wEx%n-----------------------<<<*>>>-----------------------%n'
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2.server.authorization: INFO
security:
  authentication-lockout:
    user-max-attempts: 5
    user-observation-window: 15m
    user-lock-duration: 15m
    client-max-attempts: 10
    client-observation-window: 10m
    client-lock-duration: 10m
