--liquibase formatted sql
/* https://docs.liquibase.com/concepts/changelogs/sql-format.html */

--changeset m_kalantari:1 context:table-creation
CREATE TABLE DEZHBAN.USER_PASSWORD_CREDENTIAL
(
    USER_ID       NUMBER   (10, 0)         NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_AT   TIMESTAMP WITH TIME ZONE         ,
    EXPIRES_AT    TIMESTAMP WITH TIME ZONE         ,

    PASSWORD_HASH VARCHAR2(255 CHAR)        NOT NULL,


    CONSTRAINT USER_PASSWORD_CREDENTIAL_END_USER_FK FOREIGN KEY (USER_ID) REFERENCES END_USER(ID) ON DELETE CASCADE,
    CONSTRAINT USER_PASSWORD_CREDENTIAL_USER_ID_UK UNIQUE (USER_ID)
);
--rollback DROP TABLE DEZHBAN.USER_PASSWORD_CREDENTIAL;

--changeset m_kalantari:2 context:grant-access
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.USER_PASSWORD_CREDENTIAL TO APP_DEZHBAN;