--liquibase formatted sql

--changeset m_kalantari:1 context:populate-data
INSERT INTO DEZHBAN.END_USER (
    ID, CREATED_AT, SUBJECT, USERNAME, ENABLED, LOCKED, ADMIN, WEBAUTHN_HANDLE
) VALUES (
    DEZHBAN.END_USER_SEQ.NEXTVAL,
    CURRENT_TIMESTAMP,
    'b829d640-3d9b-4a8c-95bb-20425ea4f572',
    'user',
    1,
    0,
    1,
    'b829d6403d9b4a8c95bb20425ea4f572'
);

INSERT INTO DEZHBAN.USER_PASSWORD_CREDENTIAL (
    USER_ID, CREATED_AT, PASSWORD_HASH
) SELECT
    ID,
    CURRENT_TIMESTAMP,
    '{keycloak-pbkdf2}ouIvbNYmqS1GJpGttCSh/A==$M1jaZW7ndd6UJIsjkd+RFTBHCvUSIi3yDcUQS08osqt34TtpnlYkchF8TvxSeF259drfOs5c/bFitP7p8Q19uQ==$210000'
FROM DEZHBAN.END_USER
WHERE USERNAME = 'user';

INSERT INTO DEZHBAN.USER_PROFILE (
    USER_ID,
    CREATED_AT,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    NATIONAL_CODE,
    BIRTH_DATE,
    NATIONALITY,
    MOBILE_NUMBER,
    MOBILE_NUMBER_VERIFIED,
    EMAIL,
    EMAIL_VERIFIED
) SELECT
    ID,
    CURRENT_TIMESTAMP,
    'Migration',
    'User',
    'OTHER',
    '0012345678',
    '1990-01-01',
    'IR',
    '+989120000000',
    1,
    'user@dezhban.local',
    1
FROM DEZHBAN.END_USER
WHERE USERNAME = 'user';

INSERT INTO DEZHBAN.CLIENT (
    ID,
    CREATED_AT,
    CLIENT_ID,
    ENABLED,
    PUBLIC_CLIENT,
    SECRET_HASH,
    CLIENT_TYPE,
    AUTHENTICATION_METHODS,
    AUTHORIZATION_GRANT_TYPES,
    REDIRECT_URIS,
    POST_LOGOUT_REDIRECT_URI,
    SCOPES,
    CLIENT_SETTINGS,
    TOKEN_SETTINGS
) VALUES (
    DEZHBAN.CLIENT_SEQ.NEXTVAL,
    CURRENT_TIMESTAMP,
    'client',
    1,
    0,
    '{bcrypt}$2a$12$NgRfiG4MpMDp2P0EvKVcOe01wOzkYdprOFPdo4olDUPV61wXsoRqO',
    'AP',
    'CLIENT_SECRET_BASIC',
    'AUTHORIZATION_CODE,REFRESH_TOKEN,CLIENT_CREDENTIALS',
    'http://127.0.0.1:8585/callback.html',
    'http://127.0.0.1:8585/',
    'openid,sign_request:create,sign_request:read',
    '{"requireProofKey":true,"requireAuthorizationConsent":false}',
    '{}'
);

INSERT INTO DEZHBAN.AP_CLIENT_PROFILE (
    CLIENT_ID, CREATED_AT, AP_TITLE, AP_CODE, AP_CALLBACK_URL
) SELECT
    ID,
    CURRENT_TIMESTAMP,
    'Migration Client',
    'MIGRATION_CLIENT',
    'http://127.0.0.1:8585/callback.html'
FROM DEZHBAN.CLIENT
WHERE CLIENT_ID = 'client';

--rollback DELETE FROM DEZHBAN.AP_CLIENT_PROFILE WHERE AP_CODE = 'MIGRATION_CLIENT';
--rollback DELETE FROM DEZHBAN.CLIENT WHERE CLIENT_ID = 'client';
--rollback DELETE FROM DEZHBAN.USER_PROFILE WHERE USER_ID IN (SELECT ID FROM DEZHBAN.END_USER WHERE USERNAME = 'user');
--rollback DELETE FROM DEZHBAN.USER_PASSWORD_CREDENTIAL WHERE USER_ID IN (SELECT ID FROM DEZHBAN.END_USER WHERE USERNAME = 'user');
--rollback DELETE FROM DEZHBAN.END_USER WHERE USERNAME = 'user';
