--liquibase formatted sql

--changeset m_kalantari:1 context:table-creation
CREATE TABLE DEZHBAN.OAUTH2_AUTHORIZATION
(
    ID                           VARCHAR2(100 CHAR)      NOT NULL,
    REGISTERED_CLIENT_ID         VARCHAR2(100 CHAR)      NOT NULL,
    PRINCIPAL_NAME               VARCHAR2(200 CHAR)      NOT NULL,
    AUTHORIZATION_GRANT_TYPE     VARCHAR2(100 CHAR)      NOT NULL,
    AUTHORIZED_SCOPES            VARCHAR2(1000 CHAR),
    ATTRIBUTES                   BLOB,
    STATE                        VARCHAR2(500 CHAR),
    AUTHORIZATION_CODE_VALUE     BLOB,
    AUTHORIZATION_CODE_ISSUED_AT TIMESTAMP WITH TIME ZONE,
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    AUTHORIZATION_CODE_METADATA  BLOB,
    ACCESS_TOKEN_VALUE           BLOB,
    ACCESS_TOKEN_ISSUED_AT       TIMESTAMP WITH TIME ZONE,
    ACCESS_TOKEN_EXPIRES_AT      TIMESTAMP WITH TIME ZONE,
    ACCESS_TOKEN_METADATA        BLOB,
    ACCESS_TOKEN_TYPE            VARCHAR2(100 CHAR),
    ACCESS_TOKEN_SCOPES          VARCHAR2(1000 CHAR),
    OIDC_ID_TOKEN_VALUE          BLOB,
    OIDC_ID_TOKEN_ISSUED_AT      TIMESTAMP WITH TIME ZONE,
    OIDC_ID_TOKEN_EXPIRES_AT     TIMESTAMP WITH TIME ZONE,
    OIDC_ID_TOKEN_METADATA       BLOB,
    REFRESH_TOKEN_VALUE          BLOB,
    REFRESH_TOKEN_ISSUED_AT      TIMESTAMP WITH TIME ZONE,
    REFRESH_TOKEN_EXPIRES_AT     TIMESTAMP WITH TIME ZONE,
    REFRESH_TOKEN_METADATA       BLOB,
    USER_CODE_VALUE              BLOB,
    USER_CODE_ISSUED_AT          TIMESTAMP WITH TIME ZONE,
    USER_CODE_EXPIRES_AT         TIMESTAMP WITH TIME ZONE,
    USER_CODE_METADATA           BLOB,
    DEVICE_CODE_VALUE            BLOB,
    DEVICE_CODE_ISSUED_AT        TIMESTAMP WITH TIME ZONE,
    DEVICE_CODE_EXPIRES_AT       TIMESTAMP WITH TIME ZONE,
    DEVICE_CODE_METADATA         BLOB,

    CONSTRAINT OAUTH2_AUTHORIZATION_PK PRIMARY KEY (ID)
);

CREATE TABLE DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT
(
    REGISTERED_CLIENT_ID VARCHAR2(100 CHAR)  NOT NULL,
    PRINCIPAL_NAME       VARCHAR2(200 CHAR)  NOT NULL,
    AUTHORITIES          VARCHAR2(1000 CHAR) NOT NULL,

    CONSTRAINT OAUTH2_AUTHORIZATION_CONSENT_PK
        PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);
--rollback DROP TABLE DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT;
--rollback DROP TABLE DEZHBAN.OAUTH2_AUTHORIZATION;

--changeset m_kalantari:2 context:grant-access
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.OAUTH2_AUTHORIZATION TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT TO APP_DEZHBAN;
