--liquibase formatted sql

--changeset m_kalantari:1 context:table-creation
CREATE TABLE DEZHBAN.OAUTH2_AUTHORIZATION
(
    ID                        VARCHAR2(100 CHAR) NOT NULL,
    REGISTERED_CLIENT_ID      VARCHAR2(100 CHAR) NOT NULL,
    PRINCIPAL_NAME            VARCHAR2(200 CHAR) NOT NULL,
    AUTHORIZATION_DATA        BLOB               NOT NULL,
    STATE_DIGEST              VARCHAR2(64 CHAR),
    AUTHORIZATION_CODE_DIGEST VARCHAR2(64 CHAR),
    ACCESS_TOKEN_DIGEST       VARCHAR2(64 CHAR),
    OIDC_ID_TOKEN_DIGEST      VARCHAR2(64 CHAR),
    REFRESH_TOKEN_DIGEST      VARCHAR2(64 CHAR),
    USER_CODE_DIGEST          VARCHAR2(64 CHAR),
    DEVICE_CODE_DIGEST        VARCHAR2(64 CHAR),
    VERSION                   NUMBER(19, 0) DEFAULT 0 NOT NULL,

    CONSTRAINT OAUTH2_AUTHORIZATION_PK PRIMARY KEY (ID),
    CONSTRAINT OAUTH2_AUTHORIZATION_STATE_DIGEST_UK UNIQUE (STATE_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_CODE_DIGEST_UK UNIQUE (AUTHORIZATION_CODE_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_ACCESS_DIGEST_UK UNIQUE (ACCESS_TOKEN_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_ID_DIGEST_UK UNIQUE (OIDC_ID_TOKEN_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_REFRESH_DIGEST_UK UNIQUE (REFRESH_TOKEN_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_USER_CODE_DIGEST_UK UNIQUE (USER_CODE_DIGEST),
    CONSTRAINT OAUTH2_AUTHORIZATION_DEVICE_CODE_DIGEST_UK UNIQUE (DEVICE_CODE_DIGEST)
);

CREATE TABLE DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT
(
    REGISTERED_CLIENT_ID VARCHAR2(100 CHAR)  NOT NULL,
    PRINCIPAL_NAME       VARCHAR2(200 CHAR)  NOT NULL,
    AUTHORITIES          VARCHAR2(1000 CHAR) NOT NULL,

    CONSTRAINT OAUTH2_AUTHORIZATION_CONSENT_PK
        PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);
--rollback DROP TABLE DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT;
--rollback DROP TABLE DEZHBAN.OAUTH2_AUTHORIZATION;

--changeset m_kalantari:2 context:grant-access
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.OAUTH2_AUTHORIZATION TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.OAUTH2_AUTHORIZATION_CONSENT TO APP_DEZHBAN;
