--liquibase formatted sql

--changeset m_kalantari:1 context:table-creation
ALTER TABLE DEZHBAN.END_USER ADD
(
    FAILED_LOGIN_ATTEMPTS NUMBER(10, 0) DEFAULT 0 NOT NULL,
    FAILED_LOGIN_AT       TIMESTAMP WITH TIME ZONE
);

ALTER TABLE DEZHBAN.CLIENT ADD
(
    LOCKED               NUMBER(1) DEFAULT 0 NOT NULL,
    LOCK_UNTIL           TIMESTAMP WITH TIME ZONE,
    FAILED_AUTH_ATTEMPTS NUMBER(10, 0) DEFAULT 0 NOT NULL,
    FAILED_AUTH_AT       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE DEZHBAN.LOGIN_EVENT
(
    ID                   NUMBER(19, 0)         NOT NULL,
    OCCURRED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    ACTOR_TYPE           VARCHAR2(20 CHAR)     NOT NULL,
    OUTCOME              VARCHAR2(20 CHAR)     NOT NULL,
    PRESENTED_IDENTIFIER VARCHAR2(255 CHAR)    NOT NULL,
    END_USER_ID          NUMBER(10, 0),
    CLIENT_ID            NUMBER(10, 0),
    AUTHENTICATION_METHOD VARCHAR2(100 CHAR)   NOT NULL,
    FAILURE_REASON       VARCHAR2(100 CHAR),
    REMOTE_ADDRESS       VARCHAR2(45 CHAR),
    SESSION_ID           VARCHAR2(100 CHAR),

    CONSTRAINT LOGIN_EVENT_PK PRIMARY KEY (ID),
    CONSTRAINT LOGIN_EVENT_ACTOR_TYPE_CHK CHECK (ACTOR_TYPE IN ('USER', 'CLIENT')),
    CONSTRAINT LOGIN_EVENT_OUTCOME_CHK CHECK (OUTCOME IN ('SUCCESS', 'FAILURE', 'LOCKED')),
    CONSTRAINT LOGIN_EVENT_END_USER_FK FOREIGN KEY (END_USER_ID)
        REFERENCES DEZHBAN.END_USER(ID) ON DELETE SET NULL,
    CONSTRAINT LOGIN_EVENT_CLIENT_FK FOREIGN KEY (CLIENT_ID)
        REFERENCES DEZHBAN.CLIENT(ID) ON DELETE SET NULL
);

CREATE INDEX DEZHBAN.LOGIN_EVENT_OCCURRED_AT_IDX ON DEZHBAN.LOGIN_EVENT (OCCURRED_AT);
CREATE INDEX DEZHBAN.LOGIN_EVENT_IDENTIFIER_IDX
    ON DEZHBAN.LOGIN_EVENT (ACTOR_TYPE, PRESENTED_IDENTIFIER, OCCURRED_AT);

CREATE SEQUENCE DEZHBAN.LOGIN_EVENT_SEQ INCREMENT BY 1
    MAXVALUE 9000000000000000000
    MINVALUE 1
    CACHE 100;
--rollback DROP SEQUENCE DEZHBAN.LOGIN_EVENT_SEQ;
--rollback DROP TABLE DEZHBAN.LOGIN_EVENT;
--rollback ALTER TABLE DEZHBAN.CLIENT DROP (LOCKED, LOCK_UNTIL, FAILED_AUTH_ATTEMPTS, FAILED_AUTH_AT);
--rollback ALTER TABLE DEZHBAN.END_USER DROP (FAILED_LOGIN_ATTEMPTS, FAILED_LOGIN_AT);

--changeset m_kalantari:2 context:grant-access
GRANT SELECT,INSERT ON DEZHBAN.LOGIN_EVENT TO APP_DEZHBAN;
GRANT SELECT ON DEZHBAN.LOGIN_EVENT_SEQ TO APP_DEZHBAN;
