--liquibase formatted sql

--changeset m_kalantari:1 context:table-creation
ALTER TABLE DEZHBAN.END_USER ADD
(
    ADMIN   NUMBER(1) DEFAULT 0 NOT NULL,
    VERSION NUMBER(19, 0) DEFAULT 0 NOT NULL
);

ALTER TABLE DEZHBAN.CLIENT ADD
(
    VERSION NUMBER(19, 0) DEFAULT 0 NOT NULL
);
--rollback ALTER TABLE DEZHBAN.CLIENT DROP (VERSION);
--rollback ALTER TABLE DEZHBAN.END_USER DROP (ADMIN, VERSION);
