--liquibase formatted sql
/* WebAuthn user handle and platform-credential transport list columns */

--changeset m_kalantari:1 context:table-creation
ALTER TABLE DEZHBAN.END_USER ADD WEBAUTHN_HANDLE VARCHAR2(64);

UPDATE DEZHBAN.END_USER SET WEBAUTHN_HANDLE = LOWER(RAWTOHEX(SYS_GUID())) WHERE WEBAUTHN_HANDLE IS NULL;

ALTER TABLE DEZHBAN.END_USER MODIFY WEBAUTHN_HANDLE VARCHAR2(64) NOT NULL;
--rollback ALTER TABLE DEZHBAN.END_USER DROP (WEBAUTHN_HANDLE);

--changeset m_kalantari:2 context:table-creation
ALTER TABLE DEZHBAN.USER_WEBAUTHN_CREDENTIAL ADD TRANSPORTS VARCHAR2(255);

UPDATE DEZHBAN.USER_WEBAUTHN_CREDENTIAL SET TRANSPORTS = TRANSPORT WHERE TRANSPORTS IS NULL AND TRANSPORT IS NOT NULL;

ALTER TABLE DEZHBAN.USER_WEBAUTHN_CREDENTIAL DROP COLUMN TRANSPORT;
--rollback ALTER TABLE DEZHBAN.USER_WEBAUTHN_CREDENTIAL ADD TRANSPORT VARCHAR2(255);
