--liquibase formatted sql

--changeset m_kalantari:1 context:table-creation
CREATE TABLE DEZHBAN.AUTHORIZATION_SCOPE
(
    ID           NUMBER(10, 0)         NOT NULL,
    CODE         VARCHAR2(100 CHAR)     NOT NULL,
    DESCRIPTION  VARCHAR2(500 CHAR)     NOT NULL,
    SYSTEM_SCOPE NUMBER(1) DEFAULT 1   NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT AUTHORIZATION_SCOPE_PK PRIMARY KEY (ID),
    CONSTRAINT AUTHORIZATION_SCOPE_CODE_UK UNIQUE (CODE)
);

CREATE TABLE DEZHBAN.AUTHORIZATION_ROLE
(
    ID          NUMBER(10, 0)         NOT NULL,
    CODE        VARCHAR2(100 CHAR)     NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR)     NOT NULL,
    SYSTEM_ROLE NUMBER(1) DEFAULT 1   NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT AUTHORIZATION_ROLE_PK PRIMARY KEY (ID),
    CONSTRAINT AUTHORIZATION_ROLE_CODE_UK UNIQUE (CODE)
);

CREATE TABLE DEZHBAN.AUTHORIZATION_ROLE_SCOPE
(
    ROLE_ID  NUMBER(10, 0) NOT NULL,
    SCOPE_ID NUMBER(10, 0) NOT NULL,

    CONSTRAINT AUTHORIZATION_ROLE_SCOPE_PK PRIMARY KEY (ROLE_ID, SCOPE_ID),
    CONSTRAINT AUTH_ROLE_SCOPE_ROLE_FK FOREIGN KEY (ROLE_ID)
        REFERENCES DEZHBAN.AUTHORIZATION_ROLE(ID) ON DELETE CASCADE,
    CONSTRAINT AUTH_ROLE_SCOPE_SCOPE_FK FOREIGN KEY (SCOPE_ID)
        REFERENCES DEZHBAN.AUTHORIZATION_SCOPE(ID) ON DELETE CASCADE
);

CREATE TABLE DEZHBAN.END_USER_AUTHORIZATION_ROLE
(
    USER_ID NUMBER(10, 0) NOT NULL,
    ROLE_ID NUMBER(10, 0) NOT NULL,

    CONSTRAINT END_USER_AUTH_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT END_USER_AUTH_ROLE_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES DEZHBAN.END_USER(ID) ON DELETE CASCADE,
    CONSTRAINT END_USER_AUTH_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID)
        REFERENCES DEZHBAN.AUTHORIZATION_ROLE(ID) ON DELETE CASCADE
);

CREATE TABLE DEZHBAN.CLIENT_AUTHORIZATION_ROLE
(
    CLIENT_ID NUMBER(10, 0) NOT NULL,
    ROLE_ID   NUMBER(10, 0) NOT NULL,

    CONSTRAINT CLIENT_AUTH_ROLE_PK PRIMARY KEY (CLIENT_ID, ROLE_ID),
    CONSTRAINT CLIENT_AUTH_ROLE_CLIENT_FK FOREIGN KEY (CLIENT_ID)
        REFERENCES DEZHBAN.CLIENT(ID) ON DELETE CASCADE,
    CONSTRAINT CLIENT_AUTH_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID)
        REFERENCES DEZHBAN.AUTHORIZATION_ROLE(ID) ON DELETE CASCADE
);

CREATE TABLE DEZHBAN.CLIENT_AUTHORIZATION_SCOPE
(
    CLIENT_ID NUMBER(10, 0) NOT NULL,
    SCOPE_ID  NUMBER(10, 0) NOT NULL,

    CONSTRAINT CLIENT_AUTH_SCOPE_PK PRIMARY KEY (CLIENT_ID, SCOPE_ID),
    CONSTRAINT CLIENT_AUTH_SCOPE_CLIENT_FK FOREIGN KEY (CLIENT_ID)
        REFERENCES DEZHBAN.CLIENT(ID) ON DELETE CASCADE,
    CONSTRAINT CLIENT_AUTH_SCOPE_SCOPE_FK FOREIGN KEY (SCOPE_ID)
        REFERENCES DEZHBAN.AUTHORIZATION_SCOPE(ID) ON DELETE CASCADE
);
--rollback DROP TABLE DEZHBAN.CLIENT_AUTHORIZATION_SCOPE;
--rollback DROP TABLE DEZHBAN.CLIENT_AUTHORIZATION_ROLE;
--rollback DROP TABLE DEZHBAN.END_USER_AUTHORIZATION_ROLE;
--rollback DROP TABLE DEZHBAN.AUTHORIZATION_ROLE_SCOPE;
--rollback DROP TABLE DEZHBAN.AUTHORIZATION_ROLE;
--rollback DROP TABLE DEZHBAN.AUTHORIZATION_SCOPE;

--changeset m_kalantari:2 context:sequence-creation
CREATE SEQUENCE DEZHBAN.AUTHORIZATION_SCOPE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 CACHE 20;
CREATE SEQUENCE DEZHBAN.AUTHORIZATION_ROLE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 CACHE 20;
--rollback DROP SEQUENCE DEZHBAN.AUTHORIZATION_ROLE_SEQ;
--rollback DROP SEQUENCE DEZHBAN.AUTHORIZATION_SCOPE_SEQ;

--changeset m_kalantari:3 context:grant-access
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.AUTHORIZATION_SCOPE TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.AUTHORIZATION_ROLE TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.AUTHORIZATION_ROLE_SCOPE TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.END_USER_AUTHORIZATION_ROLE TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.CLIENT_AUTHORIZATION_ROLE TO APP_DEZHBAN;
GRANT SELECT,INSERT,UPDATE,DELETE ON DEZHBAN.CLIENT_AUTHORIZATION_SCOPE TO APP_DEZHBAN;
GRANT SELECT ON DEZHBAN.AUTHORIZATION_SCOPE_SEQ TO APP_DEZHBAN;
GRANT SELECT ON DEZHBAN.AUTHORIZATION_ROLE_SEQ TO APP_DEZHBAN;

--changeset m_kalantari:4 context:table-creation
ALTER TABLE DEZHBAN.CLIENT DROP CONSTRAINT CLIENT_CLIENT_TYPE_CHK;
ALTER TABLE DEZHBAN.CLIENT ADD CONSTRAINT CLIENT_CLIENT_TYPE_CHK CHECK
    (CLIENT_TYPE IN ('AP', 'RO', 'MOBILE_FIRST_PARTY', 'MOBILE_THIRD_PARTY', 'ADMIN_PANEL'));
--rollback ALTER TABLE DEZHBAN.CLIENT DROP CONSTRAINT CLIENT_CLIENT_TYPE_CHK;
--rollback ALTER TABLE DEZHBAN.CLIENT ADD CONSTRAINT CLIENT_CLIENT_TYPE_CHK CHECK (CLIENT_TYPE IN ('AP', 'RO'));

--changeset m_kalantari:5 context:populate-data
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'openid', 'OpenID Connect authentication', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'profile', 'OpenID Connect profile claims', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'offline_access', 'Issue refresh tokens for offline access', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'identity:register', 'Register the end user', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'kyc:perform', 'Perform KYC or eKYC for an end user', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'certificate:issue', 'Issue an end-user certificate', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'certificate_order:create', 'Create a certificate order', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'certificate_order:read', 'Read certificate order status', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'certificate_order:complete', 'Complete an end-user certificate order', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'sign_request:create', 'Issue a signature request', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'sign_request:read', 'Read signature requests and their status', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'sign_request:sign', 'Sign a pending signature request', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_SCOPE
    (ID, CODE, DESCRIPTION, SYSTEM_SCOPE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_SCOPE_SEQ.NEXTVAL, 'system:admin', 'Manage the MSSP system', 1, CURRENT_TIMESTAMP);

INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'END_USER', 'Registered end user', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'ADMIN', 'System administrator', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'AP', 'Application provider client', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'RO', 'Registration operator client', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'MOBILE_FIRST_PARTY', 'First-party mobile application', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'MOBILE_THIRD_PARTY', 'Limited third-party mobile application', 1, CURRENT_TIMESTAMP);
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE
    (ID, CODE, DESCRIPTION, SYSTEM_ROLE, CREATED_AT)
VALUES (DEZHBAN.AUTHORIZATION_ROLE_SEQ.NEXTVAL, 'ADMIN_PANEL', 'Administrative panel client', 1, CURRENT_TIMESTAMP);

INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'END_USER' AND S.CODE IN
    ('identity:register', 'certificate:issue', 'certificate_order:complete', 'sign_request:read', 'sign_request:sign');
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'ADMIN' AND S.CODE = 'system:admin';
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'AP' AND S.CODE IN ('sign_request:create', 'sign_request:read');
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'RO' AND S.CODE IN ('kyc:perform', 'certificate_order:create', 'certificate_order:read');
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'MOBILE_FIRST_PARTY' AND S.CODE IN
    ('identity:register', 'certificate:issue', 'certificate_order:complete', 'sign_request:read', 'sign_request:sign');
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'MOBILE_THIRD_PARTY' AND S.CODE = 'sign_request:read';
INSERT INTO DEZHBAN.AUTHORIZATION_ROLE_SCOPE (ROLE_ID, SCOPE_ID)
SELECT R.ID, S.ID FROM DEZHBAN.AUTHORIZATION_ROLE R CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
WHERE R.CODE = 'ADMIN_PANEL' AND S.CODE = 'system:admin';

