--liquibase formatted sql

--changeset m_kalantari:1 context:populate-data
INSERT INTO DEZHBAN.END_USER_AUTHORIZATION_ROLE (USER_ID, ROLE_ID)
SELECT U.ID, R.ID
  FROM DEZHBAN.END_USER U
  CROSS JOIN DEZHBAN.AUTHORIZATION_ROLE R
 WHERE U.USERNAME = 'user'
   AND R.CODE IN ('END_USER', 'ADMIN');

INSERT INTO DEZHBAN.CLIENT_AUTHORIZATION_ROLE (CLIENT_ID, ROLE_ID)
SELECT C.ID, R.ID
  FROM DEZHBAN.CLIENT C
  CROSS JOIN DEZHBAN.AUTHORIZATION_ROLE R
 WHERE C.CLIENT_ID = 'client'
   AND R.CODE = 'AP';

INSERT INTO DEZHBAN.CLIENT_AUTHORIZATION_SCOPE (CLIENT_ID, SCOPE_ID)
SELECT C.ID, S.ID
  FROM DEZHBAN.CLIENT C
  CROSS JOIN DEZHBAN.AUTHORIZATION_SCOPE S
 WHERE C.CLIENT_ID = 'client'
   AND S.CODE IN ('openid', 'sign_request:create', 'sign_request:read');
--rollback DELETE FROM DEZHBAN.CLIENT_AUTHORIZATION_SCOPE;
--rollback DELETE FROM DEZHBAN.CLIENT_AUTHORIZATION_ROLE;
--rollback DELETE FROM DEZHBAN.END_USER_AUTHORIZATION_ROLE;
